-- TechConnect Database Schema
-- Dialect: postgresql
-- Generated by export_schema.py
--
-- This file was auto-generated from SQLModel definitions.
-- Do not edit directly.

CREATE TABLE patient (
	nhc VARCHAR(50) NOT NULL, 
	sex VARCHAR(50), 
	birth_date DATE, 
	PRIMARY KEY (nhc)
);

CREATE TABLE tumor (
	biobank_code VARCHAR NOT NULL, 
	lab_code VARCHAR(100), 
	classification VARCHAR(100), 
	ap_observation VARCHAR, 
	grade VARCHAR(50), 
	organ VARCHAR(100), 
	status VARCHAR(50), 
	tnm VARCHAR(50), 
	registration_date DATE, 
	operation_date DATE, 
	patient_nhc VARCHAR NOT NULL, 
	PRIMARY KEY (biobank_code), 
	FOREIGN KEY(patient_nhc) REFERENCES patient (nhc)
);

CREATE TABLE biomodel (
	id UUID NOT NULL, 
	type VARCHAR(50), 
	description VARCHAR, 
	creation_date DATE, 
	status VARCHAR(50), 
	progresses BOOLEAN, 
	viability FLOAT, 
	tumor_biobank_code VARCHAR NOT NULL, 
	parent_trial_id UUID, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tumor_biobank_code) REFERENCES tumor (biobank_code)
);

CREATE TABLE sample (
	id UUID NOT NULL, 
	has_serum BOOLEAN, 
	has_buffy BOOLEAN, 
	has_plasma BOOLEAN, 
	biopsy_date DATE, 
	tumor_biobank_code VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tumor_biobank_code) REFERENCES tumor (biobank_code)
);

CREATE TABLE tumor_genomic_sequencing (
	id UUID NOT NULL, 
	has_data BOOLEAN, 
	data VARCHAR, 
	tumor_biobank_code VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (tumor_biobank_code), 
	FOREIGN KEY(tumor_biobank_code) REFERENCES tumor (biobank_code)
);

CREATE TABLE tumor_molecular_data (
	id UUID NOT NULL, 
	has_data BOOLEAN, 
	data VARCHAR, 
	tumor_biobank_code VARCHAR, 
	PRIMARY KEY (id), 
	UNIQUE (tumor_biobank_code), 
	FOREIGN KEY(tumor_biobank_code) REFERENCES tumor (biobank_code)
);

CREATE TABLE passage (
	id UUID NOT NULL, 
	number INTEGER, 
	description VARCHAR, 
	biomodel_id UUID NOT NULL, 
	parent_trial_id UUID, 
	PRIMARY KEY (id), 
	FOREIGN KEY(biomodel_id) REFERENCES biomodel (id)
);

CREATE TABLE trial (
	id UUID NOT NULL, 
	success BOOLEAN, 
	description VARCHAR, 
	status BOOLEAN, 
	preclinical_trials VARCHAR, 
	creation_date DATE, 
	biobank_shipment BOOLEAN, 
	biobank_arrival_date DATE, 
	passage_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(passage_id) REFERENCES passage (id)
);

CREATE TABLE cryopreservation (
	id UUID NOT NULL, 
	location VARCHAR(100), 
	cryo_date DATE, 
	vial_count INTEGER, 
	trial_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(trial_id) REFERENCES trial (id)
);

CREATE TABLE image (
	id UUID NOT NULL, 
	image_date DATE, 
	scanner_magnification INTEGER, 
	type VARCHAR(50), 
	ap_review BOOLEAN, 
	trial_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(trial_id) REFERENCES trial (id)
);

CREATE TABLE lc_trial (
	id UUID NOT NULL, 
	confluence FLOAT, 
	spheroids BOOLEAN, 
	digestion_date DATE, 
	plate_type VARCHAR(50), 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES trial (id)
);

CREATE TABLE pdo_trial (
	id UUID NOT NULL, 
	drop_count INTEGER, 
	frozen_organoid_count INTEGER, 
	organoid_count INTEGER, 
	plate_type VARCHAR(50), 
	assessment VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES trial (id)
);

CREATE TABLE pdx_trial (
	id UUID NOT NULL, 
	ffpe BOOLEAN, 
	he_slide BOOLEAN, 
	ihq_data VARCHAR, 
	has_ihq_data BOOLEAN, 
	latency_weeks FLOAT, 
	similarity FLOAT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES trial (id)
);

CREATE TABLE trial_genomic_sequencing (
	id UUID NOT NULL, 
	annotations VARCHAR, 
	trial_id UUID, 
	PRIMARY KEY (id), 
	UNIQUE (trial_id), 
	FOREIGN KEY(trial_id) REFERENCES trial (id)
);

CREATE TABLE trial_molecular_data (
	id UUID NOT NULL, 
	annotations VARCHAR, 
	trial_id UUID, 
	PRIMARY KEY (id), 
	UNIQUE (trial_id), 
	FOREIGN KEY(trial_id) REFERENCES trial (id)
);

CREATE TABLE usage_record (
	id UUID NOT NULL, 
	record_type VARCHAR(100), 
	description VARCHAR, 
	record_date DATE, 
	trial_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(trial_id) REFERENCES trial (id)
);

CREATE TABLE facs (
	id UUID NOT NULL, 
	measure VARCHAR(100), 
	measure_value FLOAT, 
	lc_trial_id UUID, 
	PRIMARY KEY (id), 
	UNIQUE (lc_trial_id), 
	FOREIGN KEY(lc_trial_id) REFERENCES lc_trial (id)
);

CREATE TABLE mouse (
	id UUID NOT NULL, 
	birth_date DATE, 
	death_cause VARCHAR(100), 
	animal_facility VARCHAR(100), 
	proex VARCHAR(50), 
	strain VARCHAR(50), 
	sex VARCHAR(20), 
	death_date DATE, 
	pdx_trial_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(pdx_trial_id) REFERENCES pdx_trial (id)
);

CREATE TABLE implant (
	id UUID NOT NULL, 
	implant_location VARCHAR(100), 
	type VARCHAR(50), 
	mouse_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(mouse_id) REFERENCES mouse (id)
);

CREATE TABLE measure (
	id UUID NOT NULL, 
	measure_date DATE, 
	measure_value FLOAT, 
	implant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(implant_id) REFERENCES implant (id)
);

