"""PDX-related entities - Implant, Measure, and Mouse."""

from datetime import date
from typing import TYPE_CHECKING, Optional, Union
from uuid import UUID, uuid4

from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .trial import PDXTrial


class Implant(SQLModel, table=True):
    """
    Implant entity - represents an implant generated by a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        implant_location: Location of the implant
        type: Type of implant
        type: Type of implant
        mouse_id: FK to Mouse
    """
    
    __tablename__ = "implant"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    implant_location: Optional[str] = Field(default=None, max_length=100)
    type: Optional[str] = Field(default=None, max_length=50)
    # Foreign keys (required - 1:N relationship with Mouse)
    mouse_id: UUID = Field(foreign_key="mouse.id", description="FK to Mouse")
    
    # Relationships
    mouse: Optional["Mouse"] = Relationship(back_populates="implants")
    measures: list["Measure"] = Relationship(back_populates="implant")


class Measure(SQLModel, table=True):
    """
    Measure entity - records size measurements for an implant over time.
    
    Attributes:
        id: Unique identifier (UUID)
        measure_date: Date of measurement
        measure_value: Size Value
        implant_id: FK to Implant
    """
    
    __tablename__ = "measure"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    measure_date: Union[date, None] = Field(default=None)
    measure_value: Optional[float] = Field(default=None)
    
    # Foreign keys (required - 1:N relationship with Implant)
    implant_id: UUID = Field(foreign_key="implant.id", description="FK to Implant")
    
    implant: Optional["Implant"] = Relationship(back_populates="measures")


class Mouse(SQLModel, table=True):
    """
    Mouse entity - represents a mouse used in a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        birth_date: Date of birth
        death_cause: Cause of death
        animal_facility: Animal facility identifier
        proex: PROEX number
        strain: Mouse strain
        sex: Biological sex
        death_date: Date of death
        pdx_trial_id: FK to PDXTrial
    """
    
    __tablename__ = "mouse"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    birth_date: Union[date, None] = Field(default=None)
    death_cause: Optional[str] = Field(default=None, max_length=100)
    animal_facility: Optional[str] = Field(default=None, max_length=100)
    proex: Optional[str] = Field(default=None, max_length=50)
    strain: Optional[str] = Field(default=None, max_length=50)
    sex: Optional[str] = Field(default=None, max_length=20)
    death_date: Union[date, None] = Field(default=None)
    
    # Foreign keys (required - 1:1 relationship with PDXTrial)
    pdx_trial_id: UUID = Field(foreign_key="pdx_trial.id", description="FK to PDXTrial")
    
    # Relationships
    pdx_trial: Optional["PDXTrial"] = Relationship(back_populates="mouse")
    implants: list["Implant"] = Relationship(back_populates="mouse")
